language: node_js
node_js:
  - "12.6.0"

cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ='Asia/Hangzhou'  # 设置时区
install:
- yarn
script:
- yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: a8bfea01371f651b000f2f769bb8f5101f707173
  local-dir: ./docs/.vuepress/dist/ ## 根据情况自定义到静态文件输出目录
  target-branch: gh-pages
  verbose: true
  on:
    branch: master