language: node_js
node_js:
  - "12.6.0"

cache:
  directories:
  - node_modules
  yarn: true
before_install:
- export TZ='Asia/Hangzhou'  # 设置时区
install:
- yarn
script:
- yarn build

after_success:
    - cd docs/.vuepress/dist
    - git init
    - git config --global user.name "yuanzhengqiang"
    - git config --global user.email "yuanzhengqiangchn@gmail.com"
    - git add -A
    - git commit -m 'deploy'
    - git push --quiet --force "https://75ceceaa18b577537df38bbd8bfbb9bc0e4e3024@github.com/yuanzhengqiang/blog.git" master:gh-pages
branches:
  only:
    - master